import type { Database } from '@ez4/database';
import type { PostgresEngine } from '@ez4/aws-aurora/client';
import type { PoolConfig } from 'pg';

import { describe, it, beforeEach, afterEach, mock } from 'node:test';
import { equal, ok, rejects } from 'node:assert/strict';
import { rootCertificates } from 'node:tls';

import pg from 'pg';

import { Client } from '@ez4/aws-aurora/client/native';

declare class TestDb extends Database.Service<PostgresEngine> {
  tables: [];
}

type Statement = string | { text: string };

type FakeConnection = {
  query: (statement: Statement) => Promise<{ rows: unknown[]; rowCount: number }>;
  release: () => void;
};

const Endpoint = 'cluster.example.us-east-1.rds.amazonaws.com';

const databaseError = (code: string, message: string) => {
  return Object.assign(new Error(message), { code });
};

const getText = (statement: Statement) => {
  return typeof statement === 'string' ? statement : statement.text;
};

/**
 * The native driver over a pg pool answered in place: what the pool is created with, how opening a
 * connection is retried while the database is unavailable, and which failed statements run again.
 */
describe('aurora native driver', () => {
  let poolOptions: PoolConfig[];
  let statements: string[];

  // Each entry answers one `pool.connect()`: an error to throw, or a connection whose `query` runs the given
  // function (which may throw).
  let connections: (Error | ((text: string) => unknown))[];

  const makeClient = () => {
    return Client.make<TestDb>({
      debug: false,
      repository: {},
      connection: {
        database: 'app_db',
        endpoint: Endpoint,
        secretArn: 'arn:aws:secretsmanager:us-east-1:000000000000:secret:rds!cluster-0',
        user: 'app'
      }
    });
  };

  beforeEach(() => {
    poolOptions = [];
    statements = [];
    connections = [];

    process.env.AWS_REGION = 'us-east-1';
    process.env.AWS_ACCESS_KEY_ID = 'AKIDEXAMPLE';
    process.env.AWS_SECRET_ACCESS_KEY = 'secret';

    mock.method(pg.Pool.prototype, 'connect', async function (this: pg.Pool & { options: PoolConfig }) {
      poolOptions.push(this.options);

      const next = connections.shift() ?? (() => [{ one: 1 }]);

      if (next instanceof Error) {
        throw next;
      }

      const connection: FakeConnection = {
        query: async (statement) => {
          const text = getText(statement);

          statements.push(text);

          const rows = next(text);

          return { rows: Array.isArray(rows) ? rows : [], rowCount: 0 };
        },
        release: () => {}
      };

      return connection;
    });
  });

  afterEach(() => {
    mock.restoreAll();
  });

  it('assert :: one connection per lambda, trusting the proxy and the cluster, signed in with iam', async () => {
    await makeClient().rawQuery('SELECT 1');

    const [options] = poolOptions;

    ok(options);

    equal(options.max, 1);
    equal(options.idleTimeoutMillis, 300000);
    equal(options.host, Endpoint);
    equal(options.user, 'app');

    const ssl = options.ssl;

    ok(ssl && typeof ssl === 'object' && Array.isArray(ssl.ca));

    equal(ssl.ca.length, rootCertificates.length + 1);
    ok(String(ssl.ca.at(-1)).includes('BEGIN CERTIFICATE'));

    ok(typeof options.password === 'function');

    const token = await options.password();

    ok(token.startsWith(`${Endpoint}:5432/?Action=connect&DBUser=app&X-Amz-Algorithm=AWS4-HMAC-SHA256`));
    ok(token.includes('%2Frds-db%2Faws4_request'));
  });

  it('assert :: the iam token is the one @aws-sdk/rds-signer builds', async (context) => {
    // Generated by `new Signer({ hostname, port: 5432, username: 'app', region: 'us-east-1' }).getAuthToken()`
    // (@aws-sdk/rds-signer 3.1127.0) with the credentials and the clock below. The driver builds the same
    // request from the SDK packages the clients already use; an SDK upgrade that changes it fails here.
    const expected =
      'db.proxy-abc.us-east-1.rds.amazonaws.com:5432/?Action=connect&DBUser=app&X-Amz-Algorithm=AWS4-HMAC-SHA256' +
      '&X-Amz-Credential=AKIDEXAMPLE%2F20260101%2Fus-east-1%2Frds-db%2Faws4_request&X-Amz-Date=20260101T000000Z' +
      '&X-Amz-Expires=900&X-Amz-Security-Token=session%2Ftoken%2Bwith%3Dspecial' +
      '&X-Amz-Signature=4c0610fb34fbe169211d6712d95ce5ed555c3dec3ff8266a3eed2a437787b7fe&X-Amz-SignedHeaders=host';

    // A named profile would take precedence over the credentials in the environment.
    const profile = process.env.AWS_PROFILE;

    delete process.env.AWS_PROFILE;

    process.env.AWS_SECRET_ACCESS_KEY = 'wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY';
    process.env.AWS_SESSION_TOKEN = 'session/token+with=special';

    try {
      await Client.make<TestDb>({
        debug: false,
        repository: {},
        connection: {
          database: 'app_db',
          endpoint: 'db.proxy-abc.us-east-1.rds.amazonaws.com',
          secretArn: 'arn:aws:secretsmanager:us-east-1:000000000000:secret:rds!cluster-0',
          user: 'app'
        }
      }).rawQuery('SELECT 1');

      const password = poolOptions[0]?.password;

      ok(typeof password === 'function');

      context.mock.timers.enable({ apis: ['Date'], now: new Date('2026-01-01T00:00:00.000Z').getTime() });

      equal(await password(), expected);
    } finally {
      delete process.env.AWS_SESSION_TOKEN;

      if (profile) {
        process.env.AWS_PROFILE = profile;
      }
    }
  });

  it('assert :: opening a connection is retried while the database is unavailable', async () => {
    connections.push(databaseError('ECONNREFUSED', 'connect ECONNREFUSED'), databaseError('57P03', 'the database system is starting up'));

    const rows = await makeClient().rawQuery('SELECT 1');

    equal(poolOptions.length, 3);
    equal(rows.length, 1);
  });

  it('assert :: an authentication failure is not retried', async () => {
    connections.push(databaseError('28P01', 'PAM authentication failed for user "app"'));

    await rejects(makeClient().rawQuery('SELECT 1'), { code: '28P01' });

    equal(poolOptions.length, 1);
  });

  it('assert :: a statement on an ended session runs again on a new connection', async () => {
    connections.push(() => {
      throw databaseError('57P05', 'terminating connection due to idle-session timeout');
    });

    const rows = await makeClient().rawQuery('SELECT 1');

    equal(rows.length, 1);
    equal(poolOptions.length, 2);
    equal(statements.length, 2);
  });

  it('assert :: a statement that fails otherwise is not run again', async () => {
    connections.push(() => {
      throw databaseError('23505', 'duplicate key value violates unique constraint');
    });

    await rejects(makeClient().rawQuery('INSERT 1'));

    equal(statements.length, 1);
  });

  it('assert :: inside a transaction, an ended session is not run again', async () => {
    connections.push((text) => {
      if (text === 'SELECT 1') {
        throw databaseError('57P05', 'terminating connection due to idle-session timeout');
      }

      return [];
    });

    await rejects(
      makeClient().transaction(async (transaction) => {
        await transaction.rawQuery('SELECT 1');
      }),
      { code: '57P05' }
    );

    equal(statements.filter((text) => text === 'SELECT 1').length, 1);
  });

  it('assert :: a transaction that cannot begin on an ended session begins on a new connection', async () => {
    connections.push((text) => {
      if (text === 'BEGIN') {
        throw databaseError('57P01', 'terminating connection due to administrator command');
      }

      return [];
    });

    await makeClient().transaction(async (transaction) => {
      await transaction.rawQuery('SELECT 1');
    });

    equal(statements.filter((text) => text === 'BEGIN').length, 2);
    equal(statements.filter((text) => text === 'COMMIT').length, 1);
  });
});
