name: Release
on:
  push:
    branches: [main]
permissions: {}
concurrency:
  group: release-main
  cancel-in-progress: false
jobs:
  release:
    uses: Gaio-AI/gaio-actions/.github/workflows/release.yml@v1
    permissions:
      contents: write
      pull-requests: write
      actions: write
      statuses: write
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{ secrets.AWS_REGION }}
